### ISSUE TITLE
你好，我想请教你一下问题，谢谢。

### ISSUE THREAD

**Issue by Meng-shanv** [DUT-LiuYang/CHIP-Task2#1]
能请问一下你的minus_soft_attention_alignment这个模型是怎么计算的吗？还有就是DecomposableAttention你是复现的论文吗？还是有修改的。怎么我看到DecomposableAttention那些的复现很多呢，你这个好简洁，能麻烦你给我讲解一下吗？我的邮箱是895875773@qq.com，非常感谢！

**Comment by DUT-LiuYang** [comment]
因为DecomposableAttention那里只实现了相似矩阵的计算，后面attention加权等操作是在layer外面做的（因为也不涉及到权重了）。
minus_soft_attention_alignment就包含了后面的操作，具体其实就是句子A的每个单词减去句子B的每个单词的向量，然后经过一个非线性层tanh，最后再乘一个权重向量得到一个分值。用这个分值做softmax计算attention值。
DecomposableAttention我没详细看过那篇论文，我实现的是ESIM那篇，我这些ESIM系列代码都是在kaggle上的ESIM代码修改的。
我写了个总结：
https://www.jianshu.com/p/5c92a3aab822

**Comment by Meng-shanv** [comment]
哈哈哈   感谢大佬  给我回复了，我看到你那个compose attention了  我拿出来自己跑了一遍  看了每个地方的  矩阵变化，求出来就是相似关系，相似计算你是用的两个矩阵参数来做的哈？是这样的吗？  就是  再请问一下  你这个attention是按照论文里面的那种来实现的吗？还是自己做了一点改变




| |
高萌
|
|
邮箱：gaomeng_13@163.com
|

签名由 网易邮箱大师 定制

在2020年03月05日 17:52，DUT-LiuYang 写道：

因为DecomposableAttention那里只实现了相似矩阵的计算，后面attention加权等操作是在layer外面做的（因为也不涉及到权重了）。
minus_soft_attention_alignment就包含了后面的操作，具体其实就是句子A的每个单词减去句子B的每个单词的向量，然后经过一个非线性层tanh，最后再乘一个权重向量得到一个分值。用这个分值做softmax计算attention值。
DecomposableAttention我没详细看过那篇论文，我实现的是ESIM那篇，我这些ESIM系列代码都是在kaggle上的ESIM代码修改的。
我写了个总结：
https://www.jianshu.com/p/5c92a3aab822

**Comment by DUT-LiuYang** [comment]
做了一点改变，原来的论文可能是直接点积。不过也有其他论文尝试过各种计算方式的。
相似计算，相减绝对值后有两步计算，可以看作权重矩阵参数哈。

**Comment by Meng-shanv** [comment]
谢谢 大佬  指点，大佬现在还在上学哈？


| |
高萌
|
|
邮箱：gaomeng_13@163.com
|

签名由 网易邮箱大师 定制

在2020年03月06日 14:59，DUT-LiuYang 写道：

做了一点改变，原来的论文可能是直接点积。不过也有其他论文尝试过各种计算方式的。
相似计算，相减绝对值后有两步计算，可以看作权重矩阵参数哈。

**Comment by DUT-LiuYang** [comment]
已经工作了都
